### ISSUE TITLE
WASM load gtfb error

### ISSUE THREAD

**Issue by happydpc** [tedsta/wgpu-pbr#1]
Because it use the Rayon, and "The global thread pool has not been initialized.: ThreadPoolBuildError".

![20200510113247](https://user-images.githubusercontent.com/771776/81490243-28872180-92b2-11ea-886a-b11bd44c537c.png)

**Comment by tedsta** [comment]
Hmm are you using the `wasm` branch? I have it on a separate branch because it uses the master branch of `wgpu-rs` instead version 0.5 from crates.io.

**Comment by happydpc** [comment]
Yes, I test the wasm branch.

**Comment by tedsta** [comment]
There's a build script at `scripts/build-web-demo.sh` (sorry it's not documented). Try this:

```
mkdir -p target/generated/
# Build with the wasm target
RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --release --target wasm32-unknown-unknown --example basic
# Generate bindings in a `target/generated` directory
wasm-bindgen --out-dir target/generated --web target/wasm32-unknown-unknown/release/examples/basic.wasm

cp scripts/index.html target/generated/
```

Can you give that a try and let me know how it goes?
