### ISSUE TITLE
example basic not working

### ISSUE THREAD

**Issue by PravinKumar95** [tedsta/wgpu-pbr#3]
cannot run the provided example. file I/O error

**Comment by tedsta** [comment]
Hi, thanks for the report. Indeed I forgot to update the assets when I switched to a SciFiHelmet.glb with embedded textures rather than SciFiHelment.gltf which referred to textures in separate files. I just uploaded the latest assets, so if you re-download the assets it should work.

**Comment by PravinKumar95** [comment]
Now, the example works fine. Thanks
